services:
  postgres-challenge:
    restart: 'always'
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=myexpense'
      - 'POSTGRES_PASSWORD=my-db-P@ssw!!d'
      - 'POSTGRES_USER=myexpense'
    ports:
      - '5432:5432'
